### ISSUE TITLE
Sjplot and stargazer for all models 

### ISSUE THREAD

**Issue by julietteganne** [jhollway/RISP062#12]

**Comment by julietteganne** [comment]
https://www.r-bloggers.com/2017/10/one-function-to-rule-them-all-visualization-of-regression-models-in-rstats-w-sjplot/

**Comment by jhollway** [comment]
But last year at least sjPlot didn't offer methods/extensions to multinomial logistic regression packages, and I think it may also not offer anything for text or network analysis?
