### ISSUE TITLE
Review the review articles and send the okay to students

### ISSUE THREAD

**Issue by julietteganne** [jhollway/RISP062#17]

**Comment by jhollway** [comment]
Which weeks would each of these articles be reviewed? It's not always so clear...

**Comment by julietteganne** [comment]
I change the name of the folders to make it clearer.

**Comment by jhollway** [comment]
Thanks. Can you reach out to those who have not yet specified a week? We want a reasonable distribution, so maybe ask them to which of the remaining weeks this paper is supposed to relate?
