### ISSUE TITLE
Correct office hours/syllabus

### ISSUE THREAD

**Issue by jhollway** [jhollway/RISP062#3]

**Comment by julietteganne** [comment]
In addition for students to be able to meet me by appointment, I also set office hours on Wednesdays from 1-3 if you want to add this information to the syllabus.

**Comment by jhollway** [comment]
With any particular link for an appointment slot or so?

**Comment by julietteganne** [comment]
https://calendar.google.com/calendar/u/0/selfsched?sstoken=UUtycEhrV1dCSXQyfGRlZmF1bHR8MDNmOTI5NTE2MTViMDViMzczZjAyMTY5NDQ3OWI3ZDY
